import { Button, LineEdit } from "std-widgets.slint";
import { BaseField } from "base.slint";

export component AuthorizationField inherits BaseField {
    callback auth(string, string);

    GridLayout {
        spacing: 20px;
        padding: 50px;

        Row {
            Text {
                height: 50px;
                horizontal-alignment: center;
                text: @tr("Authorization");
                font-size: 18px;
            }
        }
        Row {
            username := LineEdit {
                width: 200px;
                placeholder-text: @tr("Username");
            }
        }
        Row {
            password := LineEdit {
                width: 200px;
                placeholder-text: @tr("Password");
            }
        }
        Row {
            button := Button {
                enabled: root.showed;
                height: 30px;
                text: @tr("Login");
                clicked => {
                    auth(username.text, password.text);
                }
            }
        }
    }
}