import { Button, LineEdit } from "std-widgets.slint";
import { FieldBase } from "base.slint";
import { SimpleButton } from "../components/button.slint";

export component LoginField inherits FieldBase {
    callback login(string, string);
    callback register_request();

    rows: 5;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := VerticalLayout {
        spacing: 20px;
        padding: 25px;

        Text {
            height: 50px;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: @tr("Login");
            font-size: 18px;
        }
        username := LineEdit {
            placeholder-text: @tr("Username");
        }
        pass := LineEdit {
            input-type: InputType.password;
            placeholder-text: @tr("Password");
        }
        Button {
            enabled: root.showed;
            text: @tr("Login");
            clicked => {
                login(username.text, pass.text);
            }
        }
        SimpleButton {
            vertical-stretch: 0;
            text: @tr("Don't have account?");

            hover-additional-width: 10px;

            preferred-width: self.text-length;
            preferred-height: 12px;

            clicked => { register_request(); }
        }
    }
}

export component RegisterField inherits FieldBase {
    callback register(string, string, string, string);
    callback login_request();

    rows: 7;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := VerticalLayout {
        spacing: 20px;
        padding: 25px;

        Text {
            height: 50px;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: @tr("Registration");
            font-size: 18px;
        }
        username := LineEdit {
            placeholder-text: @tr("Username");
        }
        pass := LineEdit {
            input-type: InputType.password;
            placeholder-text: @tr("Password");
        }
        verify := LineEdit {
            input-type: password;
            placeholder-text: @tr("Verify password");
        }
        key := LineEdit {
            input-type: password;
            placeholder-text: @tr("Secret key");
        }
        Button {
            enabled: root.showed;
            text: @tr("Register");
            clicked => {
                register(username.text, pass.text, verify.text, key.text);
            }
        }
        SimpleButton {
            text: @tr("Have account?");

            hover-additional-width: 10px;

            preferred-width: self.text-length;
            preferred-height: 12px;

            clicked => { login_request(); }
        }
    }
}