export component FieldBackground inherits Rectangle {
    in property <bool> enabled;
    in property <duration> change-duration;
    in property <brush> field-color <=> self.background;

    border-radius: 15px;

    animate opacity, height, width {
        duration: change-duration;
        easing: ease-in-quart;
    }

    states [
        enabled when enabled: {
            opacity: 1.0;
            visible: true;
        }

        enabled when !enabled: {
            opacity: 0.0;
            visible: self.opacity > 0;
        }
    ]
}

export component FieldBase {
    in property <bool> showed: false;
    in property <duration> change-duration;
    in property <int> rows;
    in property <length> header-height: 50px;

    public pure function calculate_height(padding: length, spacing: length) -> length {
        return header-height + 30px * (rows - 1) + padding * 2 + spacing * (rows - 1); // 30 - default row size
    }

    states [
        showed when showed: {
            opacity: 1.0;
            visible: true;

            in {
                animate opacity {
                    delay: change-duration;
                    duration: change-duration;
                }
            }
        }

        hided when !showed: {
            opacity: 0.0;
            visible: self.opacity > 0;

            in {
                animate opacity  {
                    delay: 0;
                    duration: change-duration;
                }
            }
        }
    ]

    @children
}