import { Button, LineEdit } from "std-widgets.slint";
import { FieldBase } from "base.slint";

export component ConnectionFiled inherits FieldBase {
    callback connect(string); 

    rows: 3;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := VerticalLayout {
        spacing: 20px;
        padding: 30px;

        Text {
            height: 50px;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: @tr("Enter your server address");
            font-size: 16px;
        }
        server_addr_line := LineEdit {
            placeholder-text: @tr("e.g. localhost:8080");
        }
        Button {
            enabled: root.showed;
            text: @tr("Connect");
            clicked => {
                connect(server_addr_line.text)
            }
        }
    }
}