import { Button, LineEdit } from "std-widgets.slint";
import { BaseGridField } from "base.slint";

export component ConnectionFiled inherits BaseGridField {
    callback connect(string); 

    height: 235px;

    Row {
        Text {
            height: 35px;
            horizontal-alignment: center;
            text: @tr("Enter your server address");
            font-size: 16px;
        }
    }
    Row {
        server_addr_line := LineEdit {
            height: 30px;
            placeholder-text: @tr("e.g. localhost:8080");
        }
    }
    Row {
        conn_button := Button {
            enabled: root.showed;
            height: 30px;
            text: @tr("Connect");
            clicked => {
                connect(server_addr_line.text)
            }
        }
    }
}