import { Button, LineEdit } from "std-widgets.slint";

export component ConnectionFiled {
    in property <bool> showed <=> conn_button.enabled;
    in property <duration> change-duration;

    callback connect(string);

    GridLayout {
        spacing: 30px;
        padding: 50px;

        Row {
            Text {
                height: 35px;
                horizontal-alignment: center;
                text: @tr("Enter your server address");
                font-size: 16px;
            }
        }
        Row {
            server_addr_line := LineEdit {
                height: 30px;
                width: 200px;
                placeholder-text: @tr("e.g. localhost:8080");
            }
        }
        Row {
            conn_button := Button {
                height: 30px;
                text: @tr("Connect");
                clicked => {
                    connect(server_addr_line.text)
                }
            }
        }
    }

    states [
        showed when showed: {
            opacity: 1.0;
            visible: true;

            in {
                animate opacity {
                    delay: change-duration;
                    duration: change-duration;
                }
            }
        }

        hided when !showed: {
            opacity: 0.0;
            visible: self.opacity > 0;

            in {
                animate opacity {
                    delay: 0;
                    duration: change-duration;
                }
            }
        }
    ]
}