import { FieldBackground } from "base.slint";
import { SimpleButton } from "../components/button.slint";

//* From mhserver-api 1.3.x
// Note: AI - LLM service
export enum Services { Empty, Files, Music, Images, AI }

component ServiceButton inherits SimpleButton {
    preferred-height: 45px;
    preferred-width: 45px;

    hover-additional-width: 10px;
    border-radius: 10px;

    icon-color: white;
}

component ManageSeparator {
    height: 1px;
    Rectangle {
        width: parent.width - 2px * 2;
        background: gray;
    }
}

component ManageButton inherits SimpleButton {
    use-native-scale: true;
    hover-color: whitesmoke;
}

component ManageField inherits PopupWindow {
    private property <int> items: 3;
    private property <length> item-height: 40px;

    width: 225px;
    height: item-height * items;

    callback properties-clicked();
    callback downloads-open-clicked();
    callback quit-clicked();

    FieldBackground {
        enabled: true;
        border-width: 1px;
        border-color: gray;
        field-color: black;
    }

    VerticalLayout {
        ManageButton {
            text: @tr("Properties");
            clicked => { properties-clicked() }
        }

        ManageSeparator {}

        ManageButton {
            text: @tr("Downloads directory");
            clicked => { downloads-open-clicked() }
        }

        ManageButton {
            text: @tr("Quit");
            clicked => { quit-clicked() }
        }
    }
}

export component ServiceField inherits FieldBackground {
    private property <int> service_count: 4;

    callback service_triggered(Services);
    callback properties_clicked();
    callback open_downloads_clicked();
    callback quit_clicked();

    width: 65px;
    border-radius: 0px;
    field-color: black;

    VerticalLayout {
        y: 0px;
        height: (50px + self.spacing) * service_count;

        padding: 15px;
        spacing: 15px;
        
        ServiceButton {
            icon: @image-url("../assets/files-service.png");
            clicked => { service_triggered(Services.Files) }
        }

        ServiceButton {
            icon: @image-url("../assets/images-service.png");
            clicked => { service_triggered(Services.Images) }
        }

        ServiceButton {
            icon: @image-url("../assets/music-service.png");
            clicked => { service_triggered(Services.Music) }
        }

        ServiceButton {
            icon: @image-url("../assets/llm-service.png");
            clicked => { service_triggered(Services.AI) }
        }
    }

    ServiceButton {
        preferred-width: 30px;
        preferred-height: 30px;

        y: root.height - self.preferred-height - 15px;

        icon: @image-url("../assets/settings.png");
        clicked => { manage.show() }
    }

    manage := ManageField {
        x: parent.width + 2px;
        y: parent.height - self.height - 2px;

        properties-clicked => { properties_clicked() }
        downloads-open-clicked => { open_downloads_clicked() }
        quit-clicked => { quit_clicked() }
    }
}