import { FieldBackground } from "base.slint";
import { SimpleButton } from "../components/button.slint";

//* From mhserver-api 1.3.x
// Note: AI - LLM service
export enum Services { Empty, Files, Music, Images, AI }

component ServiceButton inherits SimpleButton {
    preferred-height: 45px;
    preferred-width: 45px;

    hover-additional-width: 10px;
    border-radius: 10px;

    icon-color: white;
}

export component ServiceField inherits FieldBackground {
    private property <int> service_count: 4;
    callback service_triggered(Services);

    width: 65px;

    border-radius: 0px;
    border-bottom-right-radius: 15px;
    border-top-right-radius: 15px;

    field-color: black;

    VerticalLayout {
        y: 0px;
        height: (50px + self.spacing) * service_count;

        padding: 15px;
        spacing: 15px;
        
        ServiceButton {
            icon: @image-url("../assets/files-service.png");
            clicked => { service_triggered(Services.Files) }
        }

        ServiceButton {
            icon: @image-url("../assets/images-service.png");
            clicked => { service_triggered(Services.Images) }
        }

        ServiceButton {
            icon: @image-url("../assets/music-service.png");
            clicked => { service_triggered(Services.Music) }
        }

        ServiceButton {
            icon: @image-url("../assets/llm-service.png");
            clicked => { service_triggered(Services.AI) }
        }
    }

    ServiceButton {
        preferred-width: 30px;
        preferred-height: 30px;

        y: root.height - self.preferred-height - 15px;

        icon: @image-url("../assets/settings.png");
    }
}