export component SimpleButton {
    in property <bool> enabled: true;
    in property <image> icon <=> image.source;
    in property <brush> icon-color <=> image.colorize;
    
    in property <brush> hover-color <=> hover.background;
    in property <length> hover-additional-width: 5px;
    in-out property <length> border-radius <=> hover.border-radius;
    in property <percent> hover-max-opacity: 15%;
    in property <percent> hover-min-opacity: 0%;

    in property <string> text <=> text.text;
    in property <length> font-size <=> text.font-size;
    out property <length> text-length <=> text.width;

    in property <bool> use-native-scale: false;
    private property <length> components-width: use-native-scale ? self.width : self.preferred-width;
    private property <length> components-height: use-native-scale ? self.height : self.preferred-height;

    // Touch area fields provide
    out property <bool> has-hover <=> touch.has-hover;
    out property <length> mouse-x <=> touch.mouse-x;
    out property <length> mouse-y <=> touch.mouse-y;
    callback clicked <=> touch.clicked;
    callback pointer-event <=> touch.pointer-event;
    callback double-clicked <=> touch.double-clicked;

    touch := TouchArea {
        width: components-width + hover-additional-width;
        height: components-height + hover-additional-width;
    }

    hover := Rectangle {
        background: whitesmoke;
        width: components-width + hover-additional-width;
        height: components-height + hover-additional-width;
        border-radius: components-height / 2;

        opacity: touch.has-hover ? hover-max-opacity : hover-min-opacity;
        animate opacity { duration: 150ms; }
    }

    text := Text {
        overflow: elide;
        horizontal-alignment: center;
        vertical-alignment: center;
        color: parent.enabled ? white : gray;
    }

    image := Image {
        image-rendering: smooth;
        height: components-height;
        width: components-width;
    }
}
