export component ProgressIndicator {
    in property <float> progress: 0.0;
    in property <brush> color: blue;
    in property <length> border-radius: self.height / 2;
    in-out property <duration> update_duration: 500ms;

    height: 10px;

    // Background
    back := Rectangle {
        border-radius: root.border-radius;
        border-width: 2px;
        border-color: gray;
        background: #222020;
    }

    // Progress
    Rectangle {
        x: back.border-width;
        height: parent.height - 2 * back.border-width;
        width: parent.width * progress - 2 * back.border-width;
        border-radius: root.border-radius;
        background: color;
        animate width { duration: update_duration; }
    }
}