import { FieldBackground } from "../base.slint";
import { SimpleButton } from "../../components/button.slint";

export struct File {
    name: string,
    icon: image,
    server_path: string,
}

component FileCeil {
    in property <image> file-icon <=> file-icon.source;
    in property <string> name <=> text.text;

    callback triggered <=> butt.clicked;

    butt := SimpleButton {
        hover-color: #36454F;
        hover-border-radius: 8px;
        hover-max-opacity: 0.25;

        preferred-height: parent.height;
        preferred-width: parent.width;
    }

    VerticalLayout {
        file-icon := Image {}
        text := Text {
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
}

export component FilesServiceField inherits FieldBackground {
    out property <[File]> showed_files;
    in property <length> tile-width: 64px;
    in property <length> tile-height: 64px;

    private property <length> grid-spacing: 30px;
    private property <int> cols-count: self.width / (tile-width + grid-spacing);
    private property <int> rows: Math.ceil(showed_files.length / cols-count);

    callback file_opened(string);
    callback update_showed_files([File]);

    callback make_dir();
    callback remove_dir();
    callback save_file();
    callback delete_file();

    GridLayout {
        spacing: grid-spacing;
        padding: 20px;
        y: 0px;

        height: rows * (tile-height + self.spacing) + self.padding * 2;

        for file[i] in showed_files: FileCeil {
            col: i.mod(cols-count);
            row: i / cols-count;
            
            height: tile-height;
            width: tile-width;
            file-icon: file.icon;
            name: file.name;

            triggered => {
                debug(parent.height, cols-count, rows);
                file_opened(file.name);
                debug("clicked", file.name, "file");
            }
        }
    }

    function local_update_files(files: [File]) {
        showed_files = files;
    }

    update_showed_files(files) => {
        local_update_files(files)
    }
}