import { Button, LineEdit } from "std-widgets.slint";
import { FieldBase } from "../../components/fields.slint";
import { SimpleButton } from "../../components/button.slint";
import { PreparingInternal, UpdateStatus } from "../../globals/internal/preparing.slint";
import { State, PreparingStates } from "../../globals/state.slint";

component FieldLayout inherits VerticalLayout {
    in property <string> header-text <=> header.text;
    out property <length> header-height <=> header.height;

    spacing: 20px;
    padding: 30px;

    header := Text {
        height: 50px;
        vertical-alignment: center;
        horizontal-alignment: center;
        font-size: 16px;
    }
}

export component ConnectionField inherits FieldBase {
    rows: 3;
    header-height: layout.header-height;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := FieldLayout {
        header-text: @tr("Подключение");
        
        server_addr_line := LineEdit {
            placeholder-text: @tr("Адрес сервера, например localhost:8080");
        }

        Button {
            enabled: root.enabled;
            text: @tr("Продолжить");
            clicked => {
                PreparingInternal.connect(server_addr_line.text)
            }
        }
    }
}

export component UpdateField inherits FieldBase {
    rows: 2;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := FieldLayout {
        header-text: PreparingInternal.update-status == UpdateStatus.Required ? @tr("Доступно критическое обновление") : @tr("Доступно обновление");
        
        HorizontalLayout {
            spacing: 10px;

            Button {
                text: @tr("Установить");
            }

            Button {
                enabled: PreparingInternal.update-status == UpdateStatus.Required ? false : true;
                text: @tr("Пропустить");
            }
        }
    }
}

export component LoginField inherits FieldBase {
    rows: 5;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := FieldLayout {
        header-text: @tr("Авторизация");

        username := LineEdit {
            placeholder-text: @tr("Логин");
        }

        pass := LineEdit {
            input-type: InputType.password;
            placeholder-text: @tr("Пароль");
        }

        Button {
            enabled: root.enabled;
            text: @tr("Продолжить");
            clicked => {
                PreparingInternal.login(username.text, pass.text);
            }
        }

        SimpleButton {
            vertical-stretch: 0;
            text: @tr("Зарегистрироваться");

            hover-additional-width: 10px;

            preferred-width: self.text-length;
            preferred-height: 12px;

            clicked => { State.force_preparing_state(PreparingStates.Register); }
        }
    }
}

export component RegisterField inherits FieldBase {
    rows: 7;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := FieldLayout {
        header-text: @tr("Регистрация");

        username := LineEdit {
            placeholder-text: @tr("Логин");
        }

        pass := LineEdit {
            input-type: InputType.password;
            placeholder-text: @tr("Пароль");
        }

        verify := LineEdit {
            input-type: password;
            placeholder-text: @tr("Подтвердите пароль");
        }

        key := LineEdit {
            input-type: password;
            placeholder-text: @tr("Ключ регистрации");
        }

        Button {
            enabled: root.enabled;
            text: @tr("Продолжить");
            clicked => {
                PreparingInternal.register(username.text, pass.text, verify.text, key.text);
            }
        }
        
        SimpleButton {
            text: @tr("Войти в аккаунт");

            hover-additional-width: 10px;

            preferred-width: self.text-length;
            preferred-height: 12px;

            clicked => { State.next(); }
        }
    }
}