import { Button, LineEdit } from "std-widgets.slint";
import { FieldBase } from "../../components/fields.slint";
import { SimpleButton } from "../../components/button.slint";
import { PreparingInternal } from "../../globals/internal/preparing.slint";
import { State, PreparingStates } from "../../globals/state.slint";

export component ConnectionField inherits FieldBase {
    rows: 3;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := VerticalLayout {
        spacing: 20px;
        padding: 30px;

        Text {
            height: 50px;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: @tr("Enter your server address");
            font-size: 16px;
        }
        server_addr_line := LineEdit {
            placeholder-text: @tr("e.g. localhost:8080");
        }
        Button {
            enabled: root.enabled;
            text: @tr("Connect");
            clicked => {
                PreparingInternal.connect(server_addr_line.text)
            }
        }
    }
}

export component LoginField inherits FieldBase {
    rows: 5;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := VerticalLayout {
        spacing: 20px;
        padding: 25px;

        Text {
            height: 50px;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: @tr("Login");
            font-size: 18px;
        }
        username := LineEdit {
            placeholder-text: @tr("Username");
        }
        pass := LineEdit {
            input-type: InputType.password;
            placeholder-text: @tr("Password");
        }
        Button {
            enabled: root.enabled;
            text: @tr("Login");
            clicked => {
                PreparingInternal.login(username.text, pass.text);
            }
        }
        SimpleButton {
            vertical-stretch: 0;
            text: @tr("Don't have account?");

            hover-additional-width: 10px;

            preferred-width: self.text-length;
            preferred-height: 12px;

            clicked => { State.force_preparing_state(PreparingStates.Register); }
        }
    }
}

export component RegisterField inherits FieldBase {
    rows: 7;
    height: self.calculate_height(layout.spacing, layout.padding);

    layout := VerticalLayout {
        spacing: 20px;
        padding: 25px;

        Text {
            height: 50px;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: @tr("Registration");
            font-size: 18px;
        }
        username := LineEdit {
            placeholder-text: @tr("Username");
        }
        pass := LineEdit {
            input-type: InputType.password;
            placeholder-text: @tr("Password");
        }
        verify := LineEdit {
            input-type: password;
            placeholder-text: @tr("Verify password");
        }
        key := LineEdit {
            input-type: password;
            placeholder-text: @tr("Secret key");
        }
        Button {
            enabled: root.enabled;
            text: @tr("Register");
            clicked => {
                PreparingInternal.register(username.text, pass.text, verify.text, key.text);
            }
        }
        SimpleButton {
            text: @tr("Have account?");

            hover-additional-width: 10px;

            preferred-width: self.text-length;
            preferred-height: 12px;

            clicked => { State.next(); }
        }
    }
}