import { Page } from "../page.slint";
import { LoginField, RegisterField, ConnectionField } from "fields.slint";
import { State, PreparingStates, ApplicationStates } from "../../globals/state.slint";
import { PreparingSettings } from "../../globals/settings.slint";
import { PreparingInternal } from "../../globals/internal/preparing.slint";
import { FieldBackground } from "../../components/fields.slint";

export component PreparingPage inherits Page {
    enabled: State.application == ApplicationStates.Preparing;

    // Greeting timer
    Timer {
        interval: PreparingSettings.greeting-duration;
        running: State.preparing == PreparingStates.Greeting;
        triggered => {
            State.next();
        }
    }

    field_background := FieldBackground {
        enabled: true;
    }

    connection_field := ConnectionField {
        enabled: false;
    }

    login_field := LoginField {
        enabled: false;
    }

    register_field := RegisterField {
        enabled: false;
    }

    states [
        prepare_connection when PreparingInternal.prepare-needed && State.preparing == PreparingStates.Connection: {
            connection_field.enabled: true;
            field_background.height: connection_field.height;
        }
        prepare_login when PreparingInternal.prepare-needed && State.preparing == PreparingStates.Login: {
            login_field.enabled: true;
            field_background.height: login_field.height;
        }
        prepare_register when PreparingInternal.prepare-needed && State.preparing == PreparingStates.Register: {
            register_field.enabled: true;
            field_background.height: register_field.height;
        }
        wait_preparing when !PreparingInternal.prepare-needed: {
            field_background.width: 200px;
            field_background.height: 200px;
        }
    ]
}