export enum Services {
    Empty,
    Files,
    Music,
    Images,
    AI
}

export global MainInternal {
    out property <Services> active-service: Empty;

    callback properties_clicked();
    callback open_downloads_clicked();
    callback quit_clicked();

    public function change_active_service(new_service: Services) {
        active-service = new-service;
        if new-service == Services.Files {
            FilesInternal.update_list();
        }
    }
}

export global FilesInternal {
    callback update_list();
}