export enum UpdateStatus {
    Required,
    Available,
    ServerOld,
    CantCheck,
    NotNeeded
}

export global PreparingInternal {
    in-out property <bool> prepare-needed: false;
    in-out property <UpdateStatus> update-status: UpdateStatus.NotNeeded;

    callback handle_state();

    callback login(string, string); // username, password
    callback register(string, string, string, string); // username, password, verify password, register key
    callback connect(string); // server address

    callback update_windows();
    callback update_services();
}
