import { SimpleButton, MenuButton } from "../../components/button.slint";
import { FieldBackground } from "../../components/fields.slint";
import { MainInternal, Services } from "../../globals/internal/main.slint";
import { Assets } from "../../assets/assets.slint";
import { MenuSeparator } from "../../components/base.slint";

component ServiceButton inherits SimpleButton {
    preferred-height: 45px;
    preferred-width: 45px;

    hover-additional-width: 10px;
    border-radius: 10px;

    icon-color: white;
}

component ManageField inherits PopupWindow {
    private property <int> items: 3;
    private property <length> item-height: 40px;

    width: 225px;
    height: item-height * items;

    FieldBackground {
        height: parent.height;
        width: parent.width;
        enabled: true;
    }

    VerticalLayout {
        MenuButton {
            text: @tr("Параметры");
            clicked => { MainInternal.open_properties() }
        }

        MenuSeparator {}

        MenuButton {
            text: @tr("Папка загрузок");
            clicked => { MainInternal.open_downloads() }
        }

        MenuButton {
            text: @tr("Выйти");
            clicked => { MainInternal.quit() }
        }
    }
}

export component ServiceField inherits FieldBackground {
    private property <int> service_count: 4;

    width: 65px;

    VerticalLayout {
        y: 0px;
        height: (50px + self.spacing) * service_count;

        padding: 15px;
        spacing: 15px;
        
        ServiceButton {
            icon: Assets.files-icon;
            clicked => { MainInternal.change-active-service(Services.Files) }
        }

        ServiceButton {
            icon: Assets.images-icon;
            clicked => { MainInternal.change-active-service(Services.Images) }
        }

        ServiceButton {
            icon: Assets.music-icon;
            clicked => { MainInternal.change-active-service(Services.Music) }
        }

        ServiceButton {
            icon: Assets.llm-icon;
            clicked => { MainInternal.change-active-service(Services.AI) }
        }
    }

    ServiceButton {
        preferred-width: 30px;
        preferred-height: 30px;

        y: root.height - self.preferred-height - 15px;

        icon: Assets.settings-icon;
        clicked => { manage.show() }
    }

    manage := ManageField {
        x: parent.width + 10px;
        y: parent.height - self.height;
    }
}