export global ColorSettings {
    out property <brush> field-color: #131313;
    out property <brush> field-border-color: gray;
    out property <brush> button-hover-color: whitesmoke;
    out property <brush> upload-color: #004bbb;
    out property <brush> download-color: green;
}

export global MainSettings {
    out property <duration> object-visible-duration: 1s;
}

export global FilesSettings {
    out property <duration> loader-update-interval: 1s;
}

export enum OS {
    Linux,
    Windows
}

export global PreparingSettings {
    out property <duration> greeting-duration: 2s;
    in-out property <OS> current-os;
}