/*
 * MHServer API
 *
 * API для работы с MHServer (My Home Server)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionResponse {
    #[serde(rename = "UUID")]
    pub uuid: uuid::Uuid,
    /// Размер части файла в байтах для записи или чтения
    #[serde(rename = "chunksSize")]
    pub chunks_size: i32,
    /// Количество частей файлов доступных для записи
    #[serde(rename = "chunksCount")]
    pub chunks_count: i32,
}

impl ConnectionResponse {
    pub fn new(uuid: uuid::Uuid, chunks_size: i32, chunks_count: i32) -> ConnectionResponse {
        ConnectionResponse {
            uuid,
            chunks_size,
            chunks_count,
        }
    }
}

