/*
 * MHServer API
 *
 * API для работы с MHServer (My Home Server)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionRequest {
    #[serde(rename = "directory")]
    pub directory: String,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i32>,
}

impl ConnectionRequest {
    pub fn new(directory: String, filename: String) -> ConnectionRequest {
        ConnectionRequest {
            directory,
            filename,
            size: None,
        }
    }
}

