/*
 * MHServer API
 *
 * API для работы с MHServer (My Home Server)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SaveChunk {
    /// Массив байт, представляющий собой часть файла для записи
    #[serde(rename = "chunk")]
    pub chunk: Vec<i32>,
    /// Отступ от начала файла, после которого будет сохранён чанк
    #[serde(rename = "offset")]
    pub offset: i32,
}

impl SaveChunk {
    pub fn new(chunk: Vec<i32>, offset: i32) -> SaveChunk {
        SaveChunk {
            chunk,
            offset,
        }
    }
}

