/*
 * MHServer API
 *
 * API для работы с MHServer (My Home Server)
 *
 * The version of the OpenAPI document: 2.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserLoginRequest {
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "password")]
    pub password: String,
}

impl UserLoginRequest {
    pub fn new(username: String, password: String) -> UserLoginRequest {
        UserLoginRequest {
            username,
            password,
        }
    }
}

