import { FileIcons } from "assets.slint";

import { NotificationsBlock } from "components/notifications.slint";

// Services
import { PreparingPage } from "pages/preparing/preparing.slint";
import { MainPage } from "pages/main/main.slint";

import { PreparingSettings } from "globals/settings.slint";
import { State } from "globals/state.slint";
import { NotificationsInternal } from "globals/notification.slint";
import { PreparingInternal } from "globals/internal/preparing.slint";
import { MainInternal, FilesInternal } from "globals/internal/main.slint";

export {
    FileIcons,
    PreparingSettings,
    State,
    NotificationsInternal,
    PreparingInternal,
    MainInternal,
    FilesInternal
}

export component MainWindow inherits Window {
    title: "mhserver-client";
    width: 1280px;
    height: 720px;
    background: #2d2a29;

    PreparingPage {
        width: parent.width;
        height: parent.height;
    }

    MainPage {
        width: parent.width;
        height: parent.height;
    }

    NotificationsBlock {
        x: parent.width - 300px - 10px;
        y: 10px;
        width: 300px;
        height: parent.height;
    }
}
