export global Assets {
    out property <image> close-icon: @image-url("assets/close.png");
    out property <image> error-icon: @image-url("assets/error.png");
    out property <image> files-icon: @image-url("assets/files-service.png");
    out property <image> images-icon: @image-url("assets/images-service.png");
    out property <image> info-icon: @image-url("assets/info.png");
    out property <image> llm-icon: @image-url("assets/llm-service.png");
    out property <image> music-icon: @image-url("assets/music-service.png");
    out property <image> settings-icon: @image-url("assets/settings.png");
}

export global FileIcons {
    out property <image> document: @image-url("assets/file-icons/document.png");
    out property <image> executable: @image-url("assets/file-icons/executable.png");
    out property <image> folder: @image-url("assets/file-icons/folder.png");
    out property <image> image: @image-url("assets/file-icons/image.png");
    out property <image> music: @image-url("assets/file-icons/music.png");
    out property <image> text: @image-url("assets/file-icons/text.png");
    out property <image> undefined: @image-url("assets/file-icons/undefined.png");
    out property <image> video: @image-url("assets/file-icons/video.png");
}