import { Button, LineEdit } from "std-widgets.slint";

export component ConnectionFiled inherits Rectangle {
    in property <bool> enabled <=> conn_button.enabled;
    callback connect(string);

    background: #0b0b0b80;
    border-radius: 15px;

    opacity: enabled ? 1.0 : 0.0;
    visible: self.opacity > 0;

    animate opacity, x {
        delay: 100ms;
        duration: 800ms;
        easing: ease-in;
    }

    GridLayout {
        spacing: 30px;
        padding: 50px;

        Row {
            Text {
                height: 35px;
                horizontal-alignment: center;
                text: @tr("Enter your server address");
                font-size: 16px;
            }
        }
        Row {
            server_addr_line := LineEdit {
                height: 30px;
                width: 200px;
                placeholder-text: @tr("e.g. localhost:8080");
            }
        }
        Row {
            conn_button := Button {
                height: 30px;
                text: @tr("Connect");
                clicked => {
                    connect(server_addr_line.text)
                }
            }
        }
    }
}