import { Button, LineEdit } from "std-widgets.slint";

export component ConnectionFiled inherits Rectangle {
    callback connect(string);

    background: #0b0b0b80;
    border-radius: 15px;

    GridLayout {
        spacing: 30px;
        padding: 50px;

        Row {
            Text {
                height: 35px;
                horizontal-alignment: center;
                text: @tr("Enter your server address");
                font-size: 16px;
            }
        }
        Row {
            server_addr_line := LineEdit {
                height: 30px;
                width: 200px;
                placeholder-text: @tr("e.g. localhost:8080");
            }
        }
        Row {
            Button {
                height: 30px;
                text: @tr("Connect");
                clicked => {
                    connect(server_addr_line.text)
                }
            }
        }
    }
}