import { Button, HorizontalBox } from "std-widgets.slint";

export enum NotificationType { Info, Error }

export struct NotificationInfo {
    id: string,
    type: NotificationType,
    text: string,
}

export component Notification {
    in property <bool> hided;
    in property <NotificationType> type: Info;
    in property <string> text;

    private property <length> background_padding: 15px;

    animate x, y { duration: 500ms; }

    back := Rectangle {
        background: #242829;
        height: layout.height + background_padding;
        width: layout.width + background_padding;
        border-radius: background_padding;
        border-width: 2px;
    }

    layout := HorizontalLayout {
        spacing: 10px;
        padding-right: 5px;
        padding-left: 5px;

        icon := Image {
            preferred-height: 32px;
            preferred-width: 32px;
        }
        text := Text {
            vertical-alignment: center;
            text: root.text;
        }
    }

    states [
        info when type == NotificationType.Info && !hided: {
            back.border-color: #4294ff;
            icon.source: @image-url("assets/info.png");
        }
        error when type == NotificationType.Error && !hided: {
            back.border-color: #ff0000;
            icon.source: @image-url("assets/error.png");
        }
        hided when hided: {
            root.opacity: 0.0;
            in-out {
                animate root.opacity { duration: 800ms; } 
            }
        }
    ]
}