import { Button, HorizontalBox } from "std-widgets.slint";
import { SimpleButton } from "button.slint";

export enum NotificationType { Info, Error }

export struct NotificationInfo {
    id: string,
    type: NotificationType,
    text: string,
}

export component Notification {
    in-out property <NotificationInfo> info;
    in-out property <bool> hided;

    private property <length> background_padding: 15px;
    private property <duration> animation_opacity_time: 300ms;
    private property <float> components_opacity: 1.0;

    private property <NotificationInfo> next_info;
    private property <int> update_iteration; // for update timer
    
    callback update(NotificationInfo);
    update(nx) => {
        next_info = nx;
        hided = true;
        update_timer.start();
    }
  
    update_timer := Timer {
        interval: animation_opacity_time;
        running: false;
        triggered => {
            if (update_iteration == 1) {
                info = next_info;
                hided = !hided;
            } else if (update_iteration == 2) {
                self.stop();
                update_iteration = 0;
            }
            update_iteration += 1;
        } 
    }

    back := Rectangle {
        background: #242829;
        height: layout.height + background_padding;
        width: layout.width + background_padding;
        border-radius: background_padding;
        border-width: 2px;
        opacity: components_opacity;
    }

    layout := HorizontalLayout {
        spacing: 15px;
        padding-right: 10px;
        padding-left: 10px;

        icon := Image {
            preferred-height: 28px;
            preferred-width: 28px;
            opacity: components_opacity;
        }
        text := Text {
            max-width: 500px;
            vertical-alignment: center;
            text: info.text;
            wrap: word-wrap;
            opacity: components_opacity;
        }

        SimpleButton {
            icon: @image-url("assets/close.png");
            icon-color: whitesmoke;

            hover-color: #36454F;
            hover-max-opacity: 0.8;

            preferred-width: 12px;
            preferred-height: 12px;

            opacity: components_opacity;

            clicked => { hided = !hided }
        }
    }

    states [
        info when info.type == NotificationType.Info && !hided: {
            back.border-color: #4294ff;
            icon.source: @image-url("assets/info.png");
        }
        error when info.type == NotificationType.Error && !hided: {
            back.border-color: #ff0000;
            icon.source: @image-url("assets/error.png");
        }
        hided when hided: {
            components_opacity: 0.0;
            in-out {
                animate components_opacity { duration: animation_opacity_time; } 
            }
        }
    ]
}