import { Button, HorizontalBox } from "std-widgets.slint";
import { SimpleButton } from "button.slint";

export enum NotificationType { Info, Error }

export struct NotificationInfo {
    id: string,
    type: NotificationType,
    text: string,
}

export component Notification {
    in-out property <bool> hided;
    in property <NotificationType> type: Info;
    in property <string> text;

    private property <length> background_padding: 15px;

    animate x, y { duration: 500ms; }

    back := Rectangle {
        background: #242829;
        height: layout.height + background_padding;
        width: layout.width + background_padding;
        border-radius: background_padding;
        border-width: 2px;
    }

    layout := HorizontalLayout {
        spacing: 15px;
        padding-right: 10px;
        padding-left: 10px;

        icon := Image {
            preferred-height: 28px;
            preferred-width: 28px;
        }
        text := Text {
            vertical-alignment: center;
            text: root.text;
        }

        SimpleButton {
            icon: @image-url("assets/close.png");
            icon-color: whitesmoke;

            hover-color: #36454F;
            hover-max-opacity: 0.8;

            preferred-width: 12px;
            preferred-height: 12px;

            clicked => { hided = !hided}
        }
    }

    states [
        info when type == NotificationType.Info && !hided: {
            back.border-color: #4294ff;
            icon.source: @image-url("assets/info.png");
        }
        error when type == NotificationType.Error && !hided: {
            back.border-color: #ff0000;
            icon.source: @image-url("assets/error.png");
        }
        hided when hided: {
            root.opacity: 0.0;
            in-out {
                animate root.opacity { duration: 300ms; } 
            }
        }
    ]
}