export global Assets {
    out property <image> close-icon: @image-url("close.png");
    out property <image> error-icon: @image-url("error.png");
    out property <image> files-icon: @image-url("files-service.png");
    out property <image> images-icon: @image-url("images-service.png");
    out property <image> info-icon: @image-url("info.png");
    out property <image> llm-icon: @image-url("llm-service.png");
    out property <image> music-icon: @image-url("music-service.png");
    out property <image> settings-icon: @image-url("settings.png");
}